### ISSUE TITLE
Resistance calculator: proposed new graphic and design

### ISSUE THREAD

**Issue by instantiator** [instantiator/flipper-zero-experimental-apps#6]
Kuronons (Flipper Devices discord) has proposed a new layout with clearer graphics:

![image1](https://user-images.githubusercontent.com/1856578/234870328-77b8a088-45e6-4ef1-a13b-8b623bc7f20e.png)
![image2](https://user-images.githubusercontent.com/1856578/234870331-43eab04c-fff5-4aca-b2b5-e68d446f68c9.png)
![image3](https://user-images.githubusercontent.com/1856578/234870334-c028a08e-53a3-4bbe-baec-6cdaa3a64b6b.png)
.

**Comment by Kuronons** [comment]
R3 (2 digits + multiplier)
![R3_128x64px](https://user-images.githubusercontent.com/110337784/235213325-417b0c54-d836-4c9c-bdca-ae2137165c71.png)

R4 (2 digits + multiplier + tolerance)
![R4_128x64px](https://user-images.githubusercontent.com/110337784/235213349-2e0313d2-402b-4aa6-8a78-231291675cfb.png)

R5 (3 digits + multiplier + tolerance)
![R5_128x64px](https://user-images.githubusercontent.com/110337784/235213356-5d6fa0b9-83b0-410a-9d76-b670f42c5891.png)

R6 (3 digits + multiplier + tolerance + temperature coefficient)
![R6_128x64px](https://user-images.githubusercontent.com/110337784/235213357-95a60b5c-57f3-445d-8735-d94bc1238d89.png)

8x22px black band (for band selection)
![Black_band_8x22px](https://user-images.githubusercontent.com/110337784/235213534-68611525-4666-4458-953e-16a1df8d315a.png)

X:Y positioning :
![RESISTANCE_APP - XY positions](https://user-images.githubusercontent.com/110337784/235213566-0924d6d2-6e22-483e-b1c5-17b3470cbea0.jpg)

**Comment by instantiator** [comment]
This is very cool and thank you @Kuronons. I'll gladly use these. Will let you know when there's something to look at.

**Comment by instantiator** [comment]
Made a little progress today with the new graphics. Not complete yet, as I'm going to break each band's colour into an individual text element to position directly under the band it refers to.
